// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpujwpvxavqqkbhxkxjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwdWp3cHZ4YXZxcWtiaHhreGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTM5MTcsImV4cCI6MjA1OTQyOTkxN30._DkwMrLdjPdp2fcPxZ5OvloNwHyK5T22i55dJ3ddNzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);